name: network.yml
on:
  push:
#    branches:
#      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: arn:aws:iam::605009361452:role/GitHubActionsOIDCRole
          aws-region: us-east-1
          role-session-name: gha-${{ github.run_id }}

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Cache Terraform plugins
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-terraform
          path: ./environments/aws_dev/network/.terraform

      - name: Terraform Init
        run: |
          cd ./environments/aws_dev/network
          terraform init -upgrade

      - name: Terraform Validate
        run: |
          cd ./environments/aws_dev/network
          terraform validate

      - name: Terraform Plan
        run: |
          cd ./environments/aws_dev/network
          terraform plan -out=tfplan

      - name: Upload Terraform Plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-network
          path: ./environments/aws_dev/network/tfplan

      - name: Terraform Apply
        run: |
          cd ./environments/aws_dev/network
          terraform apply -auto-approve tfplan
